language: php

php:
  - 7.0

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_script:
  - composer install
# - mysql -e 'create database creaperio_test;'
# - touch storage/database.sqlite
  - php artisan key:generate
  - php artisan jwt:generate
# - php artisan migrate --force

script:
  - vendor/bin/phpunit

matrix:
  fast_finish: true

notifications:
  email:
    recipients:
      - morissette.francis@gmail.com
    on_success: change
    on_failure: always