language: php

php:
  - 5.6
  - hhvm
  - 7.0

before_script:
  - composer install
  - mysql -e 'create database creaperio_test;'
  - php artisan key:generate
  - php artisan jwt:generate
  - php artisan migrate --force

script:
  - vendor/bin/phpunit --debug

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

notifications:
  email:
    on_success: change
    on_failure: always