<?php

namespace Tests\Auth\Repositories;

use App\Auth\Models\User;
use App\Contracts\Auth\UserRepository;
use DB;
use Faker\Factory;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class DoctrineUserRepositoryTest extends TestCase
{
    use DatabaseTransactions;

    /**
     * @var UserRepository
     */
    private $users;
    private $fakeUser;

    /**
     * Resolve our dependencies.
     */
    public function setUp()
    {
        parent::setUp();
        $this->users = $this->app->make(UserRepository::class);
    }

    /**
     * @test
     */
    public function it_instanciates_itself_properly()
    {
        $this->assertNotNull($this->users);
    }

    /**
     * @test
     */
    public function all_returns_all_users_in_the_database()
    {
        $userCount = DB::table('users')->count();

        $users = $this->users->findAll();
        $this->assertCount($userCount, $users);
    }

    /**
     * @test
     */
    public function find_by_uuid_returns_the_proper_user()
    {
        $overrides = ['username' => 'TestUser'];
        $this->createFakeUser($overrides);
        $this->seeInDatabase('users', $overrides);

        $foundUser = $this->users->findByUUID($this->fakeUser->getId());

        $this->assertEquals($this->fakeUser, $foundUser);
        $this->assertNotNull($foundUser);

        $this->removeFakeUser();
    }

    /**
     * Create a fake user with the provided overrides, rest is generated by Faker.
     *
     * @param array $overrides
     * @return User
     */
    protected function createFakeUser($overrides = [])
    {
        $faker = Factory::create();

        $userAttributes = $overrides + [
                'username' => $faker->userName,
                'firstName' => $faker->firstName,
                'lastName' => $faker->lastName,
                'email' => $faker->email,
                'password' => $faker->password(8),
            ];

        $this->fakeUser = (new User)->setUsername($userAttributes['username'])
            ->setFirstName($userAttributes['firstName'])
            ->setLastName($userAttributes['lastName'])
            ->setEmail($userAttributes['email'])
            ->setPassword($userAttributes['password']);

        $this->users->create($this->fakeUser);
        $this->users->flush($this->fakeUser);

        return $this->fakeUser;
    }

    /**
     * Removes the fake User.
     */
    protected function removeFakeUser()
    {
        $this->users->remove($this->fakeUser);
        $this->users->flush($this->fakeUser);
        $this->fakeUser = null;
    }

    /**
     * @test
     */
    public function find_by_username_returns_the_proper_user()
    {
        $overrides = ['username' => 'TestUser'];
        $this->createFakeUser($overrides);
        $this->seeInDatabase('users', $overrides);

        $foundUser = $this->users->findByUsername($this->fakeUser->getUsername());

        $this->assertEquals($this->fakeUser, $foundUser);
        $this->assertNotNull($foundUser);

        $this->removeFakeUser();
    }

    /**
     * @test
     */
    public function find_by_email_returns_the_proper_user()
    {
        $overrides = ['username' => 'TestUser'];
        $this->createFakeUser($overrides);
        $this->seeInDatabase('users', $overrides);

        $foundUser = $this->users->findByEmail($this->fakeUser->getEmail());

        $this->assertEquals($this->fakeUser, $foundUser);
        $this->assertNotNull($foundUser);

        $this->removeFakeUser();
    }
}
