<?php

namespace Tests\Core\ACL\Repositories;

use App\Contracts\ACL\PermissionRepository;
use App\Core\ACL\Models\Permission;
use DB;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class PermissionRepositoryTest extends TestCase
{
    use DatabaseMigrations;

    /**
     * @var array
     */
    private $overrides;
    /**
     * @var PermissionRepository
     */
    private $permissions;
    /**
     * @var Permission
     */
    private $fakePermission;

    /**
     * Resolve our dependencies.
     */
    public function setUp()
    {
        parent::setUp();

        $this->permissions = $this->app->make(PermissionRepository::class);
        $this->overrides = ['pattern' => 'test.permission.' . str_random(5)];
    }

    /**
     * Clean up test data.
     */
    public function tearDown()
    {
        $this->removeFakePermission();

        parent::tearDown();
    }

    /**
     * Removes the fake Permission.
     */
    protected function removeFakePermission()
    {
        if ($this->fakePermission) {
            $this->permissions->delete($this->fakePermission);
            $this->fakePermission = null;
        }
    }

    /**
     * @test
     */
    public function it_instantiates_itself_properly()
    {
        $this->assertNotNull($this->permissions);
    }

    /**
     * @test
     */
    public function all_method_returns_all_permissions_in_the_database()
    {
        factory(Permission::class)->times(10)->create();

        $permissionCount = DB::table('permissions')->count();

        $permissions = $this->permissions->findAll();

        $this->assertEquals(10, $permissionCount);
        $this->assertCount($permissionCount, $permissions);
    }

    /**
     * @test
     */
    public function find_by_id_returns_the_proper_permission()
    {
        $this->createFakePermission();

        $foundPermission = $this->permissions->findById($this->fakePermission->id);

        $this->assertEquals($this->fakePermission->fresh(), $foundPermission);
        $this->assertNotNull($foundPermission);
    }

    /**
     * Create a fake permission with the provided overrides, rest is generated by Faker.
     *
     * @return Permission
     */
    protected function createFakePermission()
    {
        $this->fakePermission = $this->permissions->create(
            factory(Permission::class)->make($this->overrides)
        );

        $this->seeInDatabase('permissions', $this->overrides);

        return $this->fakePermission;
    }

    /**
     * @test
     */
    public function find_by_pattern_returns_the_proper_permission()
    {
        $this->createFakePermission();

        $foundPermission = $this->permissions->findByPattern($this->fakePermission->pattern);

        $this->assertEquals($this->fakePermission->fresh(), $foundPermission);
        $this->assertNotNull($foundPermission);
    }

    /**
     * @test
     */
    public function it_properly_deletes_a_permission()
    {
        $this->createFakePermission();

        $this->permissions->delete($this->fakePermission);
        $this->fakePermission = null;

        $this->notSeeInDatabase('permissions', $this->overrides);
    }

    /**
     * @test
     */
    public function find_methods_return_null_instead_of_throwing_exceptions_if_no_result_is_returned()
    {
        $permission = $this->permissions->findByPattern(str_random(8));

        $this->assertNull($permission);
    }
}
